/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import { customFetch } from './custom-fetch';
export type GetIndexParams = {
name: string;
};

export type GetIndex200AnyOf = {
  error: string;
};

export type GetIndex200AnyOfTwoQuery = {
  name: string;
};

export type GetIndex200AnyOfTwo = {
  hello: string;
  query: GetIndex200AnyOfTwoQuery;
};

export type GetIndex200 = GetIndex200AnyOf | GetIndex200AnyOfTwo;

export type GetIndex422 = {
  type: 'validation';
  on: string;
  summary?: string;
  message?: string;
  found?: unknown;
  property?: string;
  expected?: string;
};

export type PostHelloBodyOne = {
  id: number;
};

export type PostHelloBodyTwo = {
  id: number;
};

export type PostHelloBodyThree = {
  id: number;
};

export type PostHello200AnyOf = {
  error: string;
};

export type PostHello200 = string | PostHello200AnyOf;

export type PostHello422 = {
  type: 'validation';
  on: string;
  summary?: string;
  message?: string;
  found?: unknown;
  property?: string;
  expected?: string;
};

export type getIndexResponse200 = {
  data: GetIndex200
  status: 200
}

export type getIndexResponse422 = {
  data: GetIndex422
  status: 422
}
    
export type getIndexResponseSuccess = (getIndexResponse200) & {
  headers: Headers;
};
export type getIndexResponseError = (getIndexResponse422) & {
  headers: Headers;
};

export type getIndexResponse = (getIndexResponseSuccess | getIndexResponseError)

export const getGetIndexUrl = (params: GetIndexParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/?${stringifiedParams}` : `/`
}

export const getIndex = async (params: GetIndexParams, options?: RequestInit): Promise<getIndexResponse> => {
  
  return customFetch<getIndexResponse>(getGetIndexUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export type postHelloResponse200 = {
  data: PostHello200
  status: 200
}

export type postHelloResponse422 = {
  data: PostHello422
  status: 422
}
    
export type postHelloResponseSuccess = (postHelloResponse200) & {
  headers: Headers;
};
export type postHelloResponseError = (postHelloResponse422) & {
  headers: Headers;
};

export type postHelloResponse = (postHelloResponseSuccess | postHelloResponseError)

export const getPostHelloUrl = () => {


  

  return `/hello`
}

export const postHello = async (postHelloBody: PostHelloBodyOne | PostHelloBodyTwo | PostHelloBodyThree, options?: RequestInit): Promise<postHelloResponse> => {
  
  return customFetch<postHelloResponse>(getPostHelloUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: JSON.stringify(
      postHelloBody,)
  }
);}
